name: Test .NET Core Desktop

env:
  Solution_Path: gtn750-fpl-installer.slnx
  Publish_Archive: release.zip
  Publish_Directory: ../publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    # Restore the application and install any dependencies
    - name: Install dependencies
      run: dotnet restore

    # Build the solution
    - name: Compile and publish solution
      run: |
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release --property:PublishDir=../publish -r win-x86 -p:PublishSingleFile=true --self-contained true

    # Archive build result
    # - name: Create artifact archive
    #  run: Compress-Archive -Path $env:Publish_Directory\* -DestinationPath $env:Publish_Directory\$env:Publish_Archive

    # Upload and archive build result
    - name: Save results
      uses: actions/upload-artifact@v4
      with:
        name: release
        path: $env:Publish_Directory\*.exe